/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, gcc 8.3.1 -fPIC -Os) */

module top_macro_design(clk, in0, in1, in2, in3, out0, out1, out2, out3);
  input clk;
  wire clk;
  input [7:0] in0;
  wire [7:0] in0;
  input [7:0] in1;
  wire [7:0] in1;
  input [7:0] in2;
  wire [7:0] in2;
  input [7:0] in3;
  wire [7:0] in3;
  output [7:0] out0;
  wire [7:0] out0;
  output [7:0] out1;
  wire [7:0] out1;
  output [7:0] out2;
  wire [7:0] out2;
  output [7:0] out3;
  wire [7:0] out3;
  simple_macro u_macro0 (
    .clk(clk),
    .din(in0),
    .dout(out0)
  );
  simple_macro u_macro1 (
    .clk(clk),
    .din(in1),
    .dout(out1)
  );
  simple_macro u_macro2 (
    .clk(clk),
    .din(in2),
    .dout(out2)
  );
  simple_macro u_macro3 (
    .clk(clk),
    .din(in3),
    .dout(out3)
  );
endmodule
